### ISSUE TITLE
Couldn't submit it

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/volunteer-form#3]
I finished but I could match the screenshots. Can you please check?
@HannahDelaney

<img width="532" alt="image" src="https://user-images.githubusercontent.com/55094325/77955872-ef18ca80-729e-11ea-8cab-a0300e6c8ccb.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/55094325/77956098-520a6180-729f-11ea-93bc-837dab04d912.png">
The spacing, mine is short.
All the screes the spacing

**Comment by HannahDelaney** [comment]
Hey! I'd say with this one, the biggest thing here is your spacing. Your font also seems like it's bigger than the example.

The best way to solve this will be to start at the top of your smallest screenshot, go through and where you see it starting to cause spacing or visual difference issues adjust accordingly (notice things like the paragraph after "Apply to be a tree planter" is not bolded in the example, but yours is, or your green area is larger, there's more space between your input lines).

It can be time consuming, but a lot of it is just getting familiar with the class naming systems we use and applying them, as this is the best way to match the samples. Things like, you've made a container class to provide spacing for your form, but you can do this with class names like "gutter" and "pad-t" and "pad-b". They're all in the cheat sheet online.

I hope this helps!
